In [1]:
import tensorflow as tf
import keras
import os

from PIL import Image
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD, RMSprop, adam
from tensorflow.keras import layers
from tensorflow.keras import models
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler

import random
import numpy as np

Using TensorFlow backend.


In [2]:
random.seed(42)
np.random.seed(42)
tf.set_random_seed(42)

cnnModel = models.Sequential()

In [114]:
'''model.add(Convolution2D(64,(3,3),input_shape=(-1,120,120,1) ))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Convolution2D(32,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))           
model.add(Convolution2D(64,(3,3)))
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dense(8))
model.add(Activation('softmax'))
model.summary()  
 '''

cnnModel.add(layers.Conv2D(32, (3,3), activation="relu", input_shape=(120,120,1) ))

cnnModel.add(layers.MaxPooling2D((2,2)))

cnnModel.add(layers.Conv2D(64, (3,3), activation="relu"))

cnnModel.add(layers.MaxPooling2D((2,2)))

cnnModel.add(layers.Conv2D(64, (3,3), activation="relu" ))

cnnModel.add(layers.Flatten())

cnnModel.add(layers.Dense(64, activation="relu" ))

cnnModel.add(layers.Dense(32, activation="relu" ))

cnnModel.add(layers.Dense(8, activation="softmax" )) # number of classes

cnnModel.summary()


             

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 118, 118, 32)      320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 59, 59, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 57, 57, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 26, 26, 64)        36928     
_________________________________________________________________
flatten_1 (Flatten)          (None, 43264)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 64)                2768960   
__________

In [93]:
'''
images=tf.keras.dataset.images

             
(X_train,Y_train),(X_test,Y_test)=images.load_data()

X_train=X_train.reshape(60000,28,28,1)
Y_train=Y_train.astype('float32')/255
             
X_test=X_test.reshape(10000,28,28,1)
Y_test=Y_test.astype('float32')/255
    
Y_train=tf.keras.utils.to_categorical(Y_train)
Y_test=tf.keras.utils.to_categorical(Y_test)
             
             
'''
X = []
y = []

imgs = []
path = "/root/Desktop/Piyush/ckpFace"
source_path=path
for child in os.listdir(source_path):
    sub_path = os.path.join(source_path, child)
    if os.path.isdir(sub_path):
        for data_file in os.listdir(sub_path):
            X_i = Image.open(os.path.join(sub_path, data_file)).convert('L')
            X_i = np.array(X_i.resize((120,120))) / 255.0
            X.append(X_i)
            y.append(child)
print(len(X))
print(y)

445
['fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'ne

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]


In [129]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, Ytrain, Ytest = train_test_split(np.array(X), np.array(y), test_size=(0.3), random_state=42, stratify = y)

Xtrain = Xtrain.reshape([-1,120,120,1])
Xtest = Xtest.reshape([-1,120,120,1])

In [116]:
cnnModel.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

cnnModel.fit(Xtrain,Ytrain,epochs=35,batch_size=64)
             
             
testLoss,testAccuracy=cnnModel.evaluate(Xtest,Ytest)
print(testAccuracy)  

Epoch 1/35
311/311 [==============================] - 7s 22ms/sample - loss: 1.9299 - acc: 0.2605
Epoch 2/35
311/311 [==============================] - 7s 21ms/sample - loss: 1.8099 - acc: 0.3312
Epoch 3/35
311/311 [==============================] - 6s 20ms/sample - loss: 1.7603 - acc: 0.3119
Epoch 4/35
311/311 [==============================] - 6s 21ms/sample - loss: 1.5823 - acc: 0.4791
Epoch 5/35
311/311 [==============================] - 6s 20ms/sample - loss: 1.4013 - acc: 0.4920
Epoch 6/35
311/311 [==============================] - 6s 21ms/sample - loss: 1.2823 - acc: 0.5788
Epoch 7/35
311/311 [==============================] - 6s 20ms/sample - loss: 1.0590 - acc: 0.6624
Epoch 8/35
311/311 [==============================] - 6s 21ms/sample - loss: 0.9165 - acc: 0.7299
Epoch 9/35
311/311 [==============================] - 6s 20ms/sample - loss: 0.7491 - acc: 0.7556
Epoch 10/35
311/311 [==============================] - 6s 21ms/sample - loss: 0.7599 - acc: 0.7267
Epoch 11/35
311/311

In [130]:
train_score=cnnModel.evaluate(Xtrain,Ytrain,verbose=0)
print('Train loss',train_score[0])
print('Train Accuracy',100*train_score[1])

test_score=cnnModel.evaluate(Xtest,Ytest,verbose=0)
print('Train loss',test_score[0])
print('Test Accuracy',100*test_score[1])


Train loss 0.0023926813529738466
Train Accuracy 100.0
Train loss 2.1059744108968705
Test Accuracy 65.67164063453674


In [131]:
predicted=cnnModel.predict(Xtest)
predicted=np.argmax(np.round(predicted),axis=1)
Ytest=np.argmax(Ytest,axis=1)
print(predicted)

[4 5 7 0 7 5 2 4 5 4 0 5 1 2 0 5 0 5 7 4 6 7 2 5 4 7 0 7 7 7 2 6 0 5 2 3 7
 0 4 5 5 6 5 4 5 2 5 7 4 5 3 7 5 6 5 0 7 6 4 7 1 2 7 5 6 6 5 7 2 3 5 5 5 5
 5 7 2 5 2 7 7 4 4 5 7 6 5 4 0 5 7 5 5 2 4 0 4 7 5 7 1 0 7 4 2 6 2 5 4 3 5
 5 5 5 0 3 1 6 2 0 5 1 2 5 5 2 5 4 5 4 5 2 6 2]


In [132]:
cm=confusion_matrix(Ytest, predicted)
print(cm)

[[ 4  1  3  0  0  2  4  0]
 [ 0  1  1  0  0  3  0  0]
 [ 2  0 12  0  0  3  1  0]
 [ 0  0  0  4  0  2  1  0]
 [ 0  1  1  0 18  1  0  0]
 [ 3  1  0  1  0 27  4  0]
 [ 4  0  0  0  0  2  1  1]
 [ 0  1  1  0  0  1  0 22]]


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]]


In [80]:
imgs = []
path = "/root/Desktop/Piyush/Facial/images"
valid_images = [".jpg",".gif",".png",".tga"]
for f in os.listdir(path):
    ext = os.path.splitext(f)[1]
    if ext.lower() not in valid_images:
        continue  
    x_i = (Image.open(os.path.join(path,f)))
    x_i= x_i.convert('L')
    x_i = np.array(x_i.resize((120,120))) / 255.0
    X.append(x_i)
    y.append(f)
    '''X_i = Image.open(os.path.join(sub_path, data_file)).convert('L')
            X_i = np.array(X_i.resize((120,120))) / 255.0
            X.append(X_i)
            y.append(child)'''